env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
  - import
  - unused-imports
rules:
  prettier/prettier: ['error']
  camelcase: 'error'
  spaced-comment: 'error'
  quotes: ['error', 'single']
  no-duplicate-imports: ['error', 'includeExports': true]
  '@typescript-eslint/no-unused-vars':
      [
        'error',
        { 'vars': 'all', 'args': 'after-used', 'ignoreRestSiblings': false },
      ]
  unused-imports/no-unused-imports': 'error'
  unused-imports/no-unused-vars:
      [
        'warn',
        {
          'vars': 'all',
          'varsIgnorePattern': '^_',
          'args': 'after-used',
          'argsIgnorePattern': '^_',
        },
      ]
  keyword-spacing: ['error', { 'before': true }]
  no-trailing-spaces: ['error', { 'ignoreComments': true }]
  import/no-unresolved: 'error'
  arrow-body-style: 'error'
  prefer-arrow-callback: 'error'
  eqeqeq': ['error', 'always']
  prefer-const: 'error'
  no-var: 'error'
  curly: 'error'
  no-else-return: 'error'
  object-curly-spacing: ['error', 'always']
  brace-style: ['error', '1tbs', { 'allowSingleLine': false }]
  strict: ['error', 'global']
settings: { 'import/resolver': { 'typescript': { true } } }
